generatorName: dart-dio
inputSpec: tools/codegen/openapi.json
outputDir: packages/api_client
additionalProperties:
  pubName: api_client
  pubLibrary: api_client.api
  useEnumExtension: true
  nullableFields: true
  serializationLibrary: built_value
